# Generated by Django 3.1.1 on 2020-11-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_model',
            old_name='books',
            new_name='book',
        ),
    ]
