# Generated by Django 3.1.1 on 2020-11-30 08:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201130_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+977', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='order_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
