# Generated by Django 3.1.1 on 2020-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksell_model',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
