# Generated by Django 3.1.1 on 2020-10-16 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell_books', '0003_auto_20201015_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksell_model',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
