# Generated by Django 3.1.1 on 2020-10-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell_books', '0004_booksell_model_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksell_model',
            name='owner',
        ),
        migrations.AddField(
            model_name='booksell_model',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booksell_model',
            name='bookname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booksell_model',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
