# Generated by Django 3.1.1 on 2020-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200922_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='middle name'),
        ),
    ]
